<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="QuotationPrinting.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\FSharp.Control.Futures\FSharp.Control.Futures.fsproj" />
    </ItemGroup>

</Project>
